# Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#
import os


class _TestDataLocations:
    """Class for storing test data paths"""

    def __init__(self):
        script_dir = os.path.dirname(os.path.abspath(__file__))

        # The root directory of the repo
        self.repo_root = os.path.realpath(os.path.join(script_dir, *([".."] * 3)))

        self.test_dir = f"{self.repo_root}/mindmap/tests/"

        # Path where intermediate data generated by tests should be stored
        self.generated_data_dir = f"{self.test_dir}/generated_data/"

        # Path to baseline datasets
        self.baseline_data_dir = f"{self.test_dir}/baseline_data/"

        # Path to additional test data
        self.test_data_dir = f"{self.test_dir}/test_data/"

        # Path to HDF5 file used in tests
        self.cube_stacking_hdf5_filepath = f"{self.test_data_dir}/1_demo_rgbd_caminfo.hdf5"
        assert os.path.exists(
            self.cube_stacking_hdf5_filepath
        ), f"HDF5 file not found: {self.cube_stacking_hdf5_filepath}"

        self.drill_in_box_hdf5_filepath = f"{self.test_data_dir}/1_demo_drill_in_box.hdf5"
        assert os.path.exists(
            self.drill_in_box_hdf5_filepath
        ), f"HDF5 file not found: {self.drill_in_box_hdf5_filepath}"

        # Path to image used for tests
        self.test_image_filepath = f"{self.test_data_dir}/0000.table_rgb.png"
        assert os.path.exists(
            self.test_image_filepath
        ), f"Test image not found: {self.test_image_filepath}"


TestDataLocations = _TestDataLocations()
